로또 미션 제출
biforest/java-lotto pull request #5
Opened 2021-04-02 15:43 UTC by pkalsh

2021-04-03 18:44 UTC, jjanggyu commented on README.md
> +- [X] 보너스 번호는 당첨 번호와 다른 번호여야 한다.
완성된 거 체크해주세요ㅎㅎ

2021-04-03 18:45 UTC, jjanggyu commented on src/main/java/lotto/domain/MatchCount.java
> +    }
isAllMatch 대신에 isSixMatch를 쓰는 건 어떨까요? 위의 다른 것들과 통일성도 주면서..

2021-04-03 18:48 UTC, jjanggyu commented on src/main/java/lotto/domain/Statistics.java
> +    private static final int IS_EQUAL_RATE = 1;
이익과 손해를 구분하는 기준이라는 1이라는 숫자를 IS_EQUAL_RATE 라는 이름으로 정해준 것이 너무 좋아요! 혹시 IS_EQUAL_RATE 대신에 본전을 치다, 손익분기점의 BREAK_EVEN_RATE를 사용하는 것은 어떨까요??

2021-04-03 18:50 UTC, jjanggyu commented on src/main/java/lotto/domain/factory/Issuer.java
> +    }
money를 입력 받고, TICKET_PRICE로 나누어서 티켓 수를 구하고, 티켓 수가 1보다 작을 때 "금액을 1000원 이상으로 입력해주세요"하는 것보다 money 값 자체를 TICKET_PRICE와 비교해서 1000원 이하일 때 출력하는게 더 좋은 것 같아요. 어떻게 생각하시나요??

2021-04-03 18:50 UTC, jjanggyu commented on src/main/java/lotto/domain/lotto/WinningNumber.java
> +        boolean isBonusMatch = lottoTicket.contains(bonusNumber);
한 줄 띄어주면 더 좋을것 같아요!

2021-04-03 18:51 UTC, jjanggyu commented on src/main/java/lotto/domain/result/GameResult.java
> +    ALL_MATCHED(MatchCount::isAllMatch, "6개 일치", 2_000_000_000);
숫자 가독성을 위해서 _를 쓰는군요! 좋은 정보 배워갑니다!!

2021-04-03 18:52 UTC, jjanggyu commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +                .collect(Collectors.toList());
Stream에 이런 것도 있군요. 더 꼼꼼히 공부해야겠네요! 좋은 정보 감사합니다:)

2021-04-03 19:01 UTC, jjanggyu reviewed
미션 수행하느라 고생 많으셨습니다!!

우선은 되게 깔끔하게 잘 짜신 것 같아요! 테스트 케이스도 자세하게 잘 나누어서 해주시고 하셔서, 리뷰 하면서 몰랐던 부분이나 제가 부족했던 부분을 많이 배워가는거 같아요!! 수고 많으셨습니다!!

2021-04-10 20:19 UTC, pkalsh commented on src/main/java/lotto/domain/factory/Issuer.java
> +    }
반영했습니다 :+1:  PurchaseAmount로 감쌌어요

2021-04-10 20:19 UTC, pkalsh commented on README.md
> +- [X] 보너스 번호는 당첨 번호와 다른 번호여야 한다.
체크 했어요 ㅎ

2021-04-10 20:21 UTC, pkalsh commented on src/main/java/lotto/domain/Statistics.java
> +    private static final int IS_EQUAL_RATE = 1;
좋은 네이밍이네요! 하지만 EQUAL_RATE도 의미가 통한다고 생각해서 굳이 바꾸지는 않았습니다 :smile:

2021-04-10 20:23 UTC, pkalsh commented on src/main/java/lotto/domain/MatchCount.java
> +    }
로또라는 실체가 분명하고 요구사항이 변경되지 않을것 같은 부분이라 전부 맞았다는 네이밍을 붙혀 봤어요.

모두 일치한다는 의미로써의 네이밍이 더 유의미하다고 생각하는데 어떻게 생각하실까요?

2021-04-11 03:40 UTC, pkalsh commented
제가 연락이 너무 늦어 희찬님께서 개인 미션 진행인줄 알고 서로 다른 코드를 작성했네요.
세션 이후에 둘이 코드 맞춰가겠습니다

2021-04-12 13:07 UTC, kouz95 requested changes
고생하셨습니다. 코드 깔끔하네요 👍
리뷰 확인해주세요~

2021-04-12 13:07 UTC, kouz95 commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +        return IntStream.range(LOTTO_NUMBER_LOWER_BOUND, LOTTO_NUMBER_UPPER_BOUND + 1)
```suggestion
        return IntStream.rangeClosed(LOTTO_NUMBER_LOWER_BOUND, LOTTO_NUMBER_UPPER_BOUND)
```

rangeClosed를 사용하면 end를 inclusive로 처리합니다 🙂

2021-04-12 13:07 UTC, kouz95 commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +public class LottoNumber {
1부터 45까지의 로또 넘버에 한해 객체를 재사용해보는 건 어떨까요?

2021-04-12 13:07 UTC, kouz95 commented on src/main/java/lotto/domain/result/GameResult.java
> +    private final String description;
description은 view의 관심사이지 않을까요?

2021-04-12 13:14 UTC, kouz95 requested changes

2021-04-12 13:14 UTC, kouz95 commented on src/test/java/lotto/LottoApplicationTest.java
> +        assertThat(true).isTrue();
바람직한 테스트는 아닌것 같습니다. 😥
나중에 테스트는 통과하는데 왜 동작 안하지? 를 마주할 수도 있을것 같아요.

위 동작을 수행 했음에도 오류가 생기지 않았다. 정도를 테스트해보는건 어떨까요?

2021-04-12 14:13 UTC, pkalsh commented on src/test/java/lotto/LottoApplicationTest.java
> +        assertThat(true).isTrue();
아 그렇게도 테스트하는 방법이 있네요 :+1:

2021-04-12 15:01 UTC, pkalsh commented on src/main/java/lotto/domain/result/GameResult.java
> +    private final String description;
동의합니다. 리뷰 반영했습니다.

2021-04-14 17:10 UTC, kouz95 approved these changes
고생하셨습니다 🙂
깔끔하네요! 👍

2021-04-14 17:10 UTC, merged